### PR TITLE
Fix spawner amount bug and sell lag issue

### PR DESCRIPTION
**Pull request by PureGero**
Fix the quantity of mob spawners received when being bought, and fix a 10 second server freeze when selling an item

### CODE REVIEW

**Comment by PureGero** [comment]
Added 2 more commits, one only deposits money if there's actually money to deposit, the other reworks commands to be actual BukkitCommands instead of listening to the PlayerCommandPreProcessEvent, this allows for tab completion in 1.13+

**Comment by PureGero** [comment]
Addresses #40

**Comment by A248** [comment]
Registering the commands in the plugin.yml allows for tab completion on **any** version, not just 1.13+.

Also, have you tested your implementation of runtime command registration?

**Comment by PureGero** [comment]
@A248 Registering the commands in the plugin.yml is not possible for GUIShop due to the dynamic nature of the commands. My runtime command registration works for all versions, not just 1.13+. The 1.13+ in the commit messages is for a different issue (ik it should be one pull request per issue, but I failed at using github).

And yes, it's been tested in 1.8 and 1.15.2, have you found an issue with it?

**Comment by A248** [comment]
Sorry, I meant to say that registering the commands allows for tab completion on any version, because you mistakenly said that it only enabled tab completion on 1.13+.

How did you get GuiShop to build? My compiler keeps throwing errors as described in issue 43 (not linked because it's unrelated to this PR).

**Pull request merged**
