### PR TITLE
4 Miscellaneous Improvements

### PR DESCRIPTION
**Pull request by A248**
## Vault Repo and Dependency Problem
The vault repository `nexus.hc.to` is unreliable and unresponsive. To fix this, it should be updated to Vault's jitpack repository. Also, Vault 1.7 should be used because 1.6 is not on the jitpack repo.

The problems with the previous vault repo are described at length: https://github.com/MilkBowl/VaultAPI/issues/69 and https://github.com/MilkBowl/VaultAPI/issues/68 as well as https://github.com/MilkBowl/Vault/issues/756.

Not only is the repository broken, it hangs until connection timeout. Since maven checks every repo for every dependency, maven must wait for a 500x error from the vault repo to proceed.

I spent a lot of time because my IDE was having problems with this. So, save yourself a lot of time and update the Vault repo.

## Data Values

In #52 , an issue is described with regards to data values. This PR fixes the problem by using ItemStack#clone, thereby preserving its information. The shop item's data value will therefore be copied by ItemStack#clone. (Additionally, to be absolutely sure that using #clone would not break anything, I read the docs on adding enchantments to items – new enchantments override, so using #clone will not change anything with regards to enchantments.)

## Shop-specific Permissions

Users have reported in the Discord that assigning permissions to some but not all of the shops will cause the global menu to be bugged. The menu items and their respective shops will be mis-mapped. To solve this, I took advantage of IF's `GuiItem.setVisible(false)`, and kept the item in the GUI as an invisible unclickable item.

## Configurable Back Button and Forward Button Names

The back and forward page navigation buttons now have configurable item names. This has been added to the config with default values "Next Page" and "Last Page".

## Converage

I have tested all but the last 2 commits. Since the last 2 commits are incredibly simple I doubt they require specialised testing. (If I have some spare time I will test them nonetheless)

### CODE REVIEW

**Comment by A248** [comment]
By the way, I tested the changes and they work absolutely fine on Paper 1.8.8.

**Comment by A248** [comment]
Added a commit for some methods in the GuiShopAPI class. Nothing major, just features I figured I would contribute upstream.

**Comment by A248** [comment]
Added last 2 improvements.

**Comment by A248** [comment]
Users from Discord report that forward and backward page button configuration is working.

**Comment by pablo67340** [comment]
Approved, excellent job my guy. The dedication is unreal!

**Pull request merged**
