### PR TITLE
Solved Shop-Specific Permissions, Better EntityType Parsing, Removed Threading, Commands Improved, Potion Details

### PR DESCRIPTION
**Pull request by A248**
**Actually Fix Shop-Specific Permissions**

I tested the changes from the previous PR and apparently `GuiItem#setVisible` has absolutely no effect. By adding some debug statements, I determined that IF's `GuiItem#setVisible(false)` and `#setVisible(true)` do absolutely nothing.

So, I made a proper fix for shop-specific permissions by incrementing the index of the item added to the ShopPane items map. Note that the solution I first considered, to use an AIR item, does not work, because NMS clones cannot be created for AIR.

The first 6 commits have been tested on Paper 1.8.8 and were found to work.

### CODE REVIEW

**Comment by A248** [comment]
A user was having trouble with the master branch build. Specifically, they could not use iron golem spawners. To solve this, I changed a few things with mob spawner entity type parsing. The modifications are described in the latest commit.

**Comment by A248** [comment]
The last commit has been tested by another user and is reported to be working.

**Comment by A248** [comment]
**Regarding GUIShop and Multithreading**
I recently analysed GUIShop's usage of a separate thread to load the shops and items on startup. I concluded that the current implementation has concurrency problems, and as I began to implement proper multithreading, I realised it would not be worth the work. Thus, it makes most sense to scrap it.

Since it is possible but unlikely that item warming does not complete until after server startup, I first intended to use a CompletableFuture to ensure that warming completes before the server is opened to players, and call `CompletableFuture.join()` when the server has finished starting (it is possible to schedule a 1-tick synchronous task which will make Bukkit run the task once all plugins have finished loading)

However, I noticed that both the item warming thread AND the main thread access Main's ITEMTABLE in Main#loadPricetable and Shop#loadItems. Thus, it would be necessary to use a ConcurrentHashMap so the threads do not interfere. I then started searching the rest of the source for potential concurrency issues.

All of this seemed like overkill to me for a GUI-based shops plugin. To put it simply, the problem is this: *Server owners and administrators may reload GUIShop at any time. If this reload utilises threading, then the entirety of GUIShop's loaded configuration, including setting values and reading values, must be thread safe.*

Although I am a fan of loading flatfiles in parallel, and I have created a thread safe implementation of such in my personal plugin [MobStackerReloaded](https://github.com/A248/MobStackerReloaded/blob/master/src/main/java/space/arim/mobstacker/MobStacker.java#L76), GUIShop is just not suited to this kind of multithreading.

**Comment by A248** [comment]
Last 3 commits are self-explanatory.

**Comment by A248** [comment]
The last 4 commits are well detailed. Nevertheless, I will provide more explanation:

1.) I realised why GUIShop checks Player#isOp (reverts some of an earlier commit in this PR).
2.) I discovered a regression caused by the last PR. ItemStack#clone was preserving IF's `IF-uuid` NBT tag. To patch this, the tag is simply cleared before the item is given to the user.
3.) GUIShop declares Vault in its plugin.yml `depends`, meaning we don't have to check if Vault is enabled. Spigot will do it for us.

4.) **I have reviewed GuiShop's commands, patched a permissions bug I found, and added the option to skip command registration.**


**_More on This_**

Command registration is enabled by default. Suppose server owners configure GUIShop to use /buy and /sell. If command registration is disabled, the /buy and /sell commands will not be added to the server's command map via reflection.

However, /guishopuser is introduced. Using `/guishopuser buy` would have the same effect as /buy previously would (before this commit). Likewise with `/guishopuser sell`. This provides the option for server owners to use `/guishopuser` subcommands instead of the direct commands themselves.

Why is this necessary? Well, for starters, accessing the command map through reflection is not exactly the best practice, so it's good to have a fallback. Second, some server owners (specifically myself) prefer to use the commands.yml to configure exactly which commands will work best for users. Using the commands.yml, one can add whatever command as an alias of another command, including aliases which point to subcommands (e.g., /buy as an alias for /guishopuser buy). From my own perspective as a server owner, this is a better practice than having plugins conduct registration dynamically. I will decide when to configure additional commands and aliases.

Thirdly, and most importantly, some other plugins might override the command map field with their own custom command map which could introduce incompatibilities. Although *this such practice* is extraordinarily unwise, and it is entirely the fault of the other plugin, there are some plugins which do this, so some users might not want GUIShop to rely on command map registration. One such user in Discord spoke to me and stated that Citizens does this, I know of another such plugin myself.

**Comment by A248** [comment]
Please review my work ;)

**Comment by A248** [comment]
**Don't merge this yet.** 1 user is reporting the command changes are bugged. I'll test this and fix.

**Comment by A248** [comment]
Add potion types. Not yet tested.

**Comment by pablo67340** [comment]
Do you think this is ready for GUIShop 8.0?

**Comment by A248** [comment]
Sounds like a plan. I've given a few users development builds with changes from this PR, and it is reported to be working fine.

**Pull request merged**
