### PR TITLE
Dynamic Pricing, GuiShop API, More Config Options, and Bugs Fixed

### PR DESCRIPTION
**Pull request by A248**
- Adds the capability for dynamic pricing in GuiShop via a config option and the DynamicPriceProvider. In the process of doing so, some of the code has become more organised.
- Establishes GuiShopAPI as a simple, easy-to-understand API class.
- Changes some minor details

**The Dynamic Pricing Framework**

If enabled, GuiShop will search for a registration for `DynamicPriceProvider`. Other plugins can register a DynamicPriceProvider with the Bukkit registration system by adding `loadBefore: [GUIShop]` to their plugin.yml. If no DynamicPriceProvider is found but dynamic pricing is enabled in the config.yml, dynamic pricing will be disabled and a message in the console will indicate that no DynamicPriceProvider was found.

When GuiShop must display the buy or sell price of an item, it will check whether dynamic pricing is enabled. In order for the dynamic price of an item to be calculable, the item must have defined, non-zero buy- and sell-price values. The DynamicPriceProvider will treat the fixed, configurable buy-price and sell-price as input parameters for whatever price equation is desired, and then, return the result of the computation back to GuiShop.

When an item is actually purchased or sold, GuiShop must inform the DynamicPriceProvider of the changes (so that the DynamicPriceProvider may *dynamically* calculate the price based on market updates). To do so, GuiShop will call DynamicPriceProvider#buyItem and #sellItem.

The DynamicPriceProvider must be able to provide computations for given quantities of an item; not just the price of a single item. This is because the price of a single item, under dynamic pricing, is volatile – therefore the DynamicPriceProvider may have to determine what the price *would be* if the player sold more than one item.

**GuiShop API**
On my server, I made an auto-sell feature which automatically sells items from a players' auto-sell-chest. However, I must manually define the prices of each item in GuiShop as well as in my own code. Therefore, I thought it better that GuiShop expose an API to enable selling items for a player in an arbitrary context – the player need not have a GUI open. This will benefit developers by allowing them to hook into GuiShop in such a way.

The GuiShopAPI class is very simple and self-explanatory. Also, its methods are well-documented. Although it only has two methods so far, this is a first step in making an API for GuiShop. (Of course, API methods should not rely on the details of internal implementations, but rather on the reality of GuiShop's features).

**Minor Changes**
- Use Economy#depositPlayer(**OfflinePlayer**, double) instead of #depositPlayer(**String**, double).
- PRICETABLE has been changed to ITEMTABLE. This way, the Sell GUI can easily lookup all the configuration options for an `Item`. Also, regarding ITEMTABLE's keys, which are string representations of `Item`s and `ItemStack` (I call these item-strings; they are used abundantly in GuiShop), I ensured the material is always uppercased and the mob type, if the item is a spawner, is always lowercased.
- Some code has been refactored/consolidated so that it is more manageable.

### CODE REVIEW

**Comment by pablo67340** [comment]
One thing that I've been planning to add is the ability for players to add items to the pricetable, without it being in the shop. Any way we could incorporate into this PR?

**Comment by A248** [comment]
It wouldn't be very hard, actually. There can just be a config option, per item, to add the item to the shop. Disabling the option would tell GuiShop not to display the item in the GUI – easily doable. I'll get started on this.

**Comment by pablo67340** [comment]
Sure thing, if whatever you don't get finished I can do tonight :D

**Comment by A248** [comment]
The `show-in-gui` option has been added to shop items' configuration. If defined and set to false, the item won't show in the Shop GUI, meaning it cannot be purchased. However, the item can still be sold via the Sell GUI, since the item will still be in the PRICETABLE.

Also, I ensured that the usage of Price corresponds to the buy price and sell price of the item. Namely, if the item has a buy price according to Item#hasBuyPrice, Price#getBuyPrice will return that buy price. If not, Price#getBuyPrice will return -1. Similarly, if the item has a sell price according to Item#hasSellPrice, Price#getSellPrice will return that sell price, or -1 if not.

**Comment by A248** [comment]
What would you think about changing the PRICETABLE to use `Item` values instead of `Price` values? This would completely do away with the Price object. This way, if the PRICETABLE returns `Item`s, the Sell GUI can use the PRICETABLE to access all item-specific config options. Currently, the Sell GUI uses the PRICETABLE to merely lookup the price, which means it can't easily access item-specific configuration.

**Comment by A248** [comment]
Changed the priority of the BlockPlaceEvent listener method to `MONITOR` from `HIGHEST`.

During the HIGHEST stage, plugins may still cancel block placement. MONITOR is a rarely-used but highly useful. Its contract is such that no plugin should cancel the event. Listeners in MONITOR *monitor* the results of the event and run logic based on that result. Thus, listeners should never cancel the event in the MONITOR priority.

**Comment by A248** [comment]
Users may set the option `use-dynamic-price` to `false` under an item defined in the shops.yml to disable dynamic pricing for it. If dynamic pricing is not globally enabled, this has no effect.

**Comment by A248** [comment]
Alright, this PR should finally be fully ready to merge. I haven't found any more bugs.

**Comment by A248** [comment]
I found an NPE caused when an entity type in shops.yml isn't valid on the specific server version. It arises when a player places a spawner bought from GuiShop. This only happened with Zombie Pigman spawners, but not any others, which lead me to conclude it was specific to the type of entity defined. Therefore, I realised it would be better to be flexible with regards to entity types, and store them as strings, and check for nullability in the place of a spawner.

Accordingly, the latest commit fixes this problem. Note: The bug was identified on Paper 1.8.8 with GuiShop from this PR.

**Comment by pablo67340** [comment]
Am I good to merge now? :P I don't want to merge with a boog in it

**Comment by A248** [comment]
Yes. It's all good.

**Comment by pablo67340** [comment]
Going to have to come up with a changelog for the spigot post, which is going to be interesting considering how much work you've put into this...

**Pull request merged**
