### PR TITLE
Make GuiShop Easier to Build from Source

### PR DESCRIPTION
**Pull request by A248**
- Fixes _ALL_ problems listed in #43 
- Ignores the eclipse preferences file by putting it into the `.gitignore`

Personal preferences, such as .settings/org.eclipse.core.resources.prefs, shouldn't be in a public repo. In order to add it to the `.gitignore`, it had to be deleted first, so that git will fully remove it from the repo. If you decide to merge this PR, I recommend you first create a copy of your eclipse prefs file. Then when you fetch the merge, you can restore it, knowing git won't track the file. Your preferences will thus be retained.

### CODE REVIEW

**Comment by pablo67340** [comment]
GUIShop has some interesting methods of building. The problem is, in order to add full 1.8 to 1.15.5 support, and I mean full, it actually requires 2 separate builds to be completed, with class merging afterwards.

You should be able to export the plugin using 1.15.5 easily without all the other shenanigans, however the plugin will not offer full item support for anything Pre 1.8. I usually do this for testing initial features, but usually by the end of making a new release, ill be using my method to export the plugin with full item functionality. 

One of the fallback methods when resolving a material name for an item, the last one actually, is to attempt to convert the material name to an item id using MatLib. It takes this item ID and attempts to create an ItemStack object using the legacy 1.8- constructor ItemStack(id, qty, (short) data);

In order to do this, I export the plugin first as 1.15.2 with 2 lines commented out. You can find these lines by searching for "compat" in both Shop.java and Quantity.java. The plugin will export with no errors, but only support 1.15.2 to 1.9 using multiple but not all resolution material methods. Secondly, I remove 1.15.2 spigot from my buildpath and replace it with 1.8.8 which contains this deprecated constructor. I also uncomment both itemstack lines in the classes I mentioned above. Now, the plugin will export with errors, however, technically Shop.java and Quantity.java will export successfully without compilation errors. Lastly, I open both the 1.15.2 and 1.8.8 versions, and copy Shop.class & Quantity.class from 1.8.8 into the 1.15.2 jar. Now, the plugin is able to create an itemstack using item id's & data values, while using material names on 1.8- and use the same material names on 1.9+. Obviously I'd like to find a much simpler method of doing this as it's extremely hacky and a pain in the ass to release, but I just don't have the time to do the research to insure full, 100% material name compatibility across all versions, in a single jar.

**Comment by A248** [comment]
Conflicts resolved.

**Comment by A248** [comment]
Build success

Screenshot 2020-03-20 at 4 14 48 PM

**Comment by pablo67340** [comment]
Remarkable work. Building is much more simple and a ton of things are fixed. Your contribution to this project is outstanding and I am sure everybody in the Discord appreciate's it greatly 💃

**Pull request merged**
